### PR TITLE
Switch focus on complex multi clause to unrelated functionality

### PR DESCRIPTION
**Pull request by josevalim**
Perhaps also worth renaming it to “unrelated multi clauses”?

### CODE REVIEW

**Review by lucasvegi — APPROVED** [review]
Great!

**Comment by lucasvegi** [comment]
Hi @josevalim ,

Your suggestion to change the name left me in doubt. Perhaps this can limit the scope of the smell. It may even apply in the context of _unrelated_ multi-clauses, but the _complexity_ of grouping many conditions, and decreasing readability, still seems to me to be an important sensitive part. This _complexity_ can also happen when multi-clauses are related.

What I'm trying to say is that I have the feeling that the complexity and the lack of relationship between the multi-clauses are different problems, but they can coexist.

Maybe it's the case that "Unrelated multi-clauses function" is a new smell, somehow related to "Complex multi-clauses function". We already did something similar with "Complex extraction in clauses", another suggestion of yours.

What do you think?

**Comment by lucasvegi** [comment]
I understand your point.

I'll think about it a little more. This type of observation made by you is very important for us to reflect and have a more global perception of the problems.

Generally speaking, code smells are context-sensitive structures. This means that a smell will not always represent pain in a specific project. It is just a possibility that must be analyzed in the context in question. Given that, if we keep "Complex multi-clauses" as the name of a smell, it might be a case of making it explicit in the documentation that not all instances of complex multi-clauses need to be refactored, but at the very least developers should analyze whether these structures are not suboptimal.

**Comment by josevalim** [comment]
> Generally speaking, code smells are context-sensitive structures. This means that a smell will not always represent pain in a specific project. 

I would say this is the main discussion point. Some smells are always wrong (or wrong 99% of the time):

* Code organization by process
* Large code generation
* Unnecessary macro
* Exceptions for flow control
* ...

But if we also have smells that are wrong some-of-the-time, it may lead people to think that:

* smells that are always wrong may be valid in some situations (which they are not)

* smells that depend on the context are treated as always wrong (i.e. they will cargo cult the smell and always consider it bad)

I guess we will have a better idea when there is a survey asking the community how much they agree or disagree with each smell? :) And then, if some smells are debatable, we can leave explicit notes saying that a particular smell is more sensitive to the context of the code.

**Pull request merged**
